### ISSUE TITLE
右侧触钮不灵敏，很难触发，左侧手感就很好很丝滑，设置完全一样。手机型号：PIxel 9pro xl

### ISSUE THREAD

**Issue by whw19822** [aaronzzx/okgesture#1]

**Comment by aaronzzx** [comment]
你试试把右边触钮宽度调大试试，看是不是这个原因

**Comment by whw19822** [comment]
https://github.com/user-attachments/assets/b6550e6d-ae13-4400-9ca8-78021aa231b8

不是，你看下这个视频

**Comment by aaronzzx** [comment]
> 20241209_102314.mp4 
> 不是，你看下这个视频

有点奇怪，我也不得其解，右侧上方区域和下方区域也是划不出来吗？首页右上角三个点里面恢复默认设置也一样吗？

**Comment by whw19822** [comment]
是，右侧上中下都划不出来，恢复默认设置也一样。但是左侧就完全正常。。

**Comment by aaronzzx** [comment]
> 是，右侧上中下都划不出来，恢复默认设置也一样。但是左侧就完全正常。。

我应该定位到问题了，下个版本解决

**Comment by aaronzzx** [comment]
> 是，右侧上中下都划不出来，恢复默认设置也一样。但是左侧就完全正常。。

更新了哦老哥，试一下还有没有这个问题，没有我就close了
